service: lambda-authorizers

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 128
  timeout: 3
  environment:
    # Add your own Auth0 tenant name
    JWKS_URI: 'https://TENANT_NAME.eu.auth0.com/.well-known/jwks.json'
    TOKEN_ISSUER: 'https://TENANT_NAME.eu.auth0.com/'

    # Add your own audience (Auth0 API identifier)
    AUDIENCE: 'https://api.danillouz.dev/account'

package:
  exclude:
    - ./*
    - ./**/*.test.js
  include:
    - node_modules
    - src

functions:
  auth0VerifyBearer:
    handler: src/auth0.verifyBearer
    description: Verifies the bearer token with the help of Auth0
